In [1]:
import numpy as np
from qiskit_ibm_runtime.options.utils import UnsetType
from scipy import optimize

In [2]:
optimize.show_options("minimize", "cobyla")

Minimize a scalar function of one or more variables using the
Constrained Optimization BY Linear Approximation (COBYLA) algorithm.
This method uses the pure-python implementation of the algorithm from PRIMA.

Options
-------
rhobeg : float
    Reasonable initial changes to the variables.
tol : float
    Final accuracy in the optimization (not precisely guaranteed).
    This is a lower bound on the size of the trust region.
disp : int
    Controls the frequency of output:
        0. (default) There will be no printing
        1. A message will be printed to the screen at the end of iteration, showing
           the best vector of variables found and its objective function value
        2. in addition to 1, each new value of RHO is printed to the screen,
           with the best vector of variables so far and its objective function
           value.
        3. in addition to 2, each function evaluation with its variables will
           be printed to the screen.
maxiter : int
    Maximum

In [3]:
def cost_func(x, a, b, c):
    # print(x)
    return a * (x[0]) ** 2 + b * (x[1]) ** 2 + c
optimizer_parameters = {
    "method": 'cobyla',
    "bounds": None,
    "constraints": (),
    "tol": None,
    "callback": None,
    "options": {"maxiter": 100,
                "disp": 2},
}

In [4]:
# noinspection PyTypeChecker
optimize.minimize(fun=cost_func,
                  x0=np.array([2.3, 3.14]),
                  args=(1, 1, 1),
                  **optimizer_parameters
                  )


Initialization step with radius = 1.0
Number of function values = 0   Least value of F = 16.1496
The corresponding X is: [2.3  3.14]

Initialization step with radius = 1.0
Number of function values = 1   Least value of F = 21.7496
The corresponding X is: [3.3  3.14]

Initialization step with radius = 1.0
Number of function values = 2   Least value of F = 23.429600000000004
The corresponding X is: [2.3  4.14]

Trust region step with radius = 1.0
Number of function values = 4   Least value of F = 9.367251848514526
The corresponding X is: [1.69028924 2.34737601]

Trust region step with radius = 2.0
Number of function values = 5   Least value of F = 2.3054766164596128
The corresponding X is: [0.09702467 1.13844755]

Trust region step with radius = 1.9999999999999998
Number of function values = 6   Least value of F = 5.31386470823723
The corresponding X is: [-1.8851294   0.87186689]

Trust region step with radius = 1.0
Number of function values = 7   Least value of F = 1.1690154283689043
T

 message: Return from COBYLA because the trust region radius reaches its lower bound.
 success: True
  status: 0
     fun: 1.0000000009143601
       x: [ 1.888e-05  2.362e-05]
    nfev: 41
   maxcv: 0.0

In [5]:
class CostFunction:
    def __init__(self,  a, b, c):
        self.a = a
        self.b = b
        self.c = c

    def __call__(self, x: np.ndarray) -> float:
        # print(x)
        return self.a * (x[0]) ** 2 + self.b * (x[1]) ** 2 + self.c

In [6]:
optimize.minimize(fun=CostFunction(1, 1, 1),
                  x0=np.array([2.3, 3.14]),
                  **optimizer_parameters
                  )


Initialization step with radius = 1.0
Number of function values = 0   Least value of F = 16.1496
The corresponding X is: [2.3  3.14]

Initialization step with radius = 1.0
Number of function values = 1   Least value of F = 21.7496
The corresponding X is: [3.3  3.14]

Initialization step with radius = 1.0
Number of function values = 2   Least value of F = 23.429600000000004
The corresponding X is: [2.3  4.14]

Trust region step with radius = 1.0
Number of function values = 4   Least value of F = 9.367251848514526
The corresponding X is: [1.69028924 2.34737601]

Trust region step with radius = 2.0
Number of function values = 5   Least value of F = 2.3054766164596128
The corresponding X is: [0.09702467 1.13844755]

Trust region step with radius = 1.9999999999999998
Number of function values = 6   Least value of F = 5.31386470823723
The corresponding X is: [-1.8851294   0.87186689]

Trust region step with radius = 1.0
Number of function values = 7   Least value of F = 1.1690154283689043
T

 message: Return from COBYLA because the trust region radius reaches its lower bound.
 success: True
  status: 0
     fun: 1.0000000009143601
       x: [ 1.888e-05  2.362e-05]
    nfev: 41
   maxcv: 0.0

In [7]:
testabc = {"a": 1, "b": 2, "c": 3}
testabc

{'a': 1, 'b': 2, 'c': 3}

In [8]:
import inspect
from qiskit_ibm_runtime import EstimatorOptions
import qiskit_ibm_runtime.options as qiskit_ibm_options
b = EstimatorOptions()

In [9]:
def check_for_option(value):
    temp = inspect.getmembers(qiskit_ibm_options, inspect.isclass)
    known_options = [x[1] for x in temp]
    result = False
    for option in known_options:
        result = result or isinstance(value, option)
    return result


def print_options(options, prefix=""):
    print(f"{prefix}{type(options).__name__}:")
    attrs = [a for a in dir(options) if not a.startswith('_') and not (callable(getattr(options, a)) or isinstance(getattr(options, a), UnsetType))]
    for attr in attrs:
        value = getattr(options, attr)
        if check_for_option(value):
            print_options(value, prefix=prefix+"\t")
        else:
            print(f"{prefix}\t{attr} = {value}")
print_options(b)

EstimatorOptions:
	DynamicalDecouplingOptions:
	EnvironmentOptions:
		callback = None
		job_tags = None
		log_level = WARNING
		private = False
	ExecutionOptionsV2:
	ResilienceOptionsV2:
		LayerNoiseLearningOptions:
		MeasureNoiseLearningOptions:
		PecOptions:
		ZneOptions:
	SimulatorOptions:
	TwirlingOptions:


In [10]:
from qiskit_aer.primitives import EstimatorV2 as AerEstimator
AerEstimator()

In [11]:
from dataclasses import asdict
b = EstimatorOptions()
asdict(b)

{'_VERSION': 2,
 'max_execution_time': Unset,
 'environment': {'log_level': 'WARNING',
  'callback': None,
  'job_tags': None,
  'private': False},
 'simulator': {'noise_model': Unset,
  'seed_simulator': Unset,
  'coupling_map': Unset,
  'basis_gates': Unset},
 'default_precision': Unset,
 'default_shots': Unset,
 'resilience_level': Unset,
 'seed_estimator': Unset,
 'dynamical_decoupling': {'enable': Unset,
  'sequence_type': Unset,
  'extra_slack_distribution': Unset,
  'scheduling_method': Unset,
  'skip_reset_qubits': Unset},
 'resilience': {'measure_mitigation': Unset,
  'measure_noise_learning': {'num_randomizations': Unset,
   'shots_per_randomization': Unset},
  'zne_mitigation': Unset,
  'zne': {'amplifier': Unset,
   'noise_factors': Unset,
   'extrapolator': Unset,
   'extrapolated_noise_factors': Unset},
  'pec_mitigation': Unset,
  'pec': {'max_overhead': Unset, 'noise_gain': Unset},
  'layer_noise_learning': {'max_layers_to_learn': Unset,
   'shots_per_randomization': Un

In [12]:
c = EstimatorOptions(
    resilience_level=2,
    resilience={"zne_mitigation": True, "zne": {"noise_factors": [1, 3, 5]}},
)
print_options(c)

EstimatorOptions:
	DynamicalDecouplingOptions:
	EnvironmentOptions:
		callback = None
		job_tags = None
		log_level = WARNING
		private = False
	ExecutionOptionsV2:
	ResilienceOptionsV2:
		LayerNoiseLearningOptions:
		MeasureNoiseLearningOptions:
		PecOptions:
		ZneOptions:
			noise_factors = [1.0, 3.0, 5.0]
		zne_mitigation = True
	resilience_level = 2
	SimulatorOptions:
	TwirlingOptions:


In [13]:
from solver.circuits import rebuild_ansatz
rebuild_ansatz(None)

TypeError: 'NoneType' object is not subscriptable

In [15]:
test_dataset = np.arange(729).reshape((3,3,3,3,3,3))
test_dataset

array([[[[[[  0,   1,   2],
           [  3,   4,   5],
           [  6,   7,   8]],

          [[  9,  10,  11],
           [ 12,  13,  14],
           [ 15,  16,  17]],

          [[ 18,  19,  20],
           [ 21,  22,  23],
           [ 24,  25,  26]]],


         [[[ 27,  28,  29],
           [ 30,  31,  32],
           [ 33,  34,  35]],

          [[ 36,  37,  38],
           [ 39,  40,  41],
           [ 42,  43,  44]],

          [[ 45,  46,  47],
           [ 48,  49,  50],
           [ 51,  52,  53]]],


         [[[ 54,  55,  56],
           [ 57,  58,  59],
           [ 60,  61,  62]],

          [[ 63,  64,  65],
           [ 66,  67,  68],
           [ 69,  70,  71]],

          [[ 72,  73,  74],
           [ 75,  76,  77],
           [ 78,  79,  80]]]],



        [[[[ 81,  82,  83],
           [ 84,  85,  86],
           [ 87,  88,  89]],

          [[ 90,  91,  92],
           [ 93,  94,  95],
           [ 96,  97,  98]],

          [[ 99, 100, 101],
           [102, 1

In [46]:
dep_sel = test_dataset[*[slice(None),1,2,0,slice(None),slice(None)]]
n_iter = np.random.randint(0,3,(3,))
dep_sel

array([[[135, 136, 137],
        [138, 139, 140],
        [141, 142, 143]],

       [[378, 379, 380],
        [381, 382, 383],
        [384, 385, 386]],

       [[621, 622, 623],
        [624, 625, 626],
        [627, 628, 629]]])

In [47]:
n_iter

array([2, 0, 2])

In [51]:
my_sel = [np.arange(3), n_iter, slice(None)]
dep_sel[*my_sel]

array([[141, 142, 143],
       [378, 379, 380],
       [627, 628, 629]])

In [62]:
flat_shape = (-1,*dep_sel.shape[-1:])
dep_sel.reshape(flat_shape).shape

(9, 3)